### ISSUE TITLE
Getting to V.1 of this repo

### ISSUE THREAD

**Issue by JosephMcArthur** [sparcopen/opencon#1]
With sections in rough order of priority... 

# Housekeeping & Introing

- [x] Set up a readme documenting what we're doing here
- [x] Getting everyone on Github
  - [x] help them get their notification set up right
- [x] Do a walkthrough for staff / oc on a call

# Issues

- [x] set up labels
- [x] set up a few key milestones 
- [ ] Document issues use (what do each things mean for our team)
- [x] Have people brain dump their thoughts into issues

# Files

- [ ] Make our drive public
- [ ] Create a document to linkout to big bits of the drive

# Launch & participation

- [x] set up git pages
- [x] set up a contribution.md
- [x] set up a page on git pages that nicely explains wtf is going on & invites people "in". 
- [x] set up the ability to submit issues over email

**Comment by JosephMcArthur** [comment]
Splitting out latter to-dos from things needed to jump start the repo for staff & oc. #8

**Comment by JosephMcArthur** [comment]
Yesterday I gave a quick update to staff here & asked them to brain dump thoughts. Ticking that to-do. 

Also started the process of getting an email set up for this repo to ease participation.

**Comment by JosephMcArthur** [comment]
The basic systems are all working here, so I'm going to close this issue and breakout further work into smaller issues.
