### ISSUE TITLE
Setting up a "pre-print" zone

### ISSUE THREAD

**Issue by JosephMcArthur** [sparcopen/opencon#2]
The aim, from emails:

> It's often a struggle to release things quickly (or they sit on the shelves forever, as we can't do them to a high enough standard). I'd like to have a place where we can share that work quickly & easily, before it's "done", essentially exactly like a pre-print. This would be "medium as the message". I can set up a totally separate, extremely lightweight site to do this so that our "unfinished" work couldn't be confused for our finished work. 

For this, using gitpages, or here generally, to help signals "unfinished but maybe helpful" is the current best plan. 

This issue is to set up that system, and roll it out to staff. I'm expecting to need:
- [ ] a place in the repo designed to do that
- [ ] give an example
- [ ] test / describe how to do this for non-markdown docs
- [ ] tell & encourage staff

Once that's done, we'll close this.

**Comment by nshockey** [comment]
Let me know if you need anything to move this forward besides, you know, time :-)
