### ISSUE TITLE
Day One Checklist

### ISSUE THREAD

**Issue by JosephMcArthur** [sparcopen/opencon#49]
This issue is for noting small things that we need to remember for the day (e.g make sure to bring X, or do Y).

**Comment by JosephMcArthur** [comment]
- [x] Check & adjust layout of breakout rooms after SOS session to get ready for unconference. Venue staff can’t do this. 
- [x] morning do testing over everything in every room with micheal. He won’t be there for most of the time. 
- [x] immediately check all rooms for SOS set up. Put table names down.
- [x] collect up spare flipcharts after the unconference for the workshops the next day 
- [ ] nightly email
- [x] joe show @KTsteen27 / Shawn / @bradyyano the print room
- [x] find hotel rooms
- [x] table clip for banner in goethe

**Comment by JosephMcArthur** [comment]
@lorrainechu3n little reminder to open a doc for the nightly email so we can all stick stuff in it as needed.

**Comment by char-siuu-bao** [comment]
Nightly logistics email you mean?

Lorraine
