### ISSUE TITLE
Launch mini-site for repo

### ISSUE THREAD

**Issue by JosephMcArthur** [sparcopen/opencon#8]
Moved from #1 

# Launch & participation

- [x] set up git pages
- [x] set up a contribution.md
- [ ] set up a page on git pages that nicely explains what is going on & invites people "in".
- [x] set up the ability to submit issues over email

**Comment by JosephMcArthur** [comment]
It's worth noting that we have both a nice landing page: https://sparcopen.github.io/opencon/ & and email cloo+sparcopen/opencon@cottagelabs.com that can be used to submit.
